In [7]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

combined_datasets = pd.read_csv("combined_dataset.csv")

X_combined = combined_datasets.drop("Activity", axis=1)
y_combined = combined_datasets["Activity"]

# Proper split: 80% train, 20% test
X_comb_train, X_comb_test, y_comb_train, y_comb_test = train_test_split(
    X_combined, y_combined, test_size=0.2, random_state=42, stratify=y_combined
)

rf_combined = RandomForestClassifier(n_estimators=100, random_state=42)
rf_combined.fit(X_comb_train, y_comb_train)
y_comb_pred = rf_combined.predict(X_comb_test)

print("=== Combined Dataset with Proper Split ===")
print(classification_report(y_comb_test, y_comb_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_comb_test, y_comb_pred))
print(f"\nTrain size: {len(X_comb_train)}, Test size: {len(X_comb_test)}")

=== Combined Dataset with Proper Split ===
                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       281
           SITTING       0.94      0.96      0.95       263
          STANDING       0.97      0.96      0.96       359
           WALKING       0.97      0.99      0.98       272
WALKING_DOWNSTAIRS       0.99      0.97      0.98       204
  WALKING_UPSTAIRS       0.99      1.00      0.99       215

          accuracy                           0.98      1594
         macro avg       0.98      0.98      0.98      1594
      weighted avg       0.98      0.98      0.98      1594


Confusion Matrix:
[[281   0   0   0   0   0]
 [  0 253   9   1   0   0]
 [  0  15 343   1   0   0]
 [  0   0   3 268   0   1]
 [  0   0   0   5 198   1]
 [  0   0   0   0   1 214]]

Train size: 6375, Test size: 1594


In [8]:
# Train with XGBoost Classifier

import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

combined_datasets = pd.read_csv("combined_dataset.csv")
X_combined = combined_datasets.drop("Activity", axis=1)
y_combined = combined_datasets["Activity"]

X_comb_train, X_comb_test, y_comb_train, y_comb_test = train_test_split(
    X_combined, y_combined, test_size=0.2, random_state=42, stratify=y_combined
)

# Encode labels to numeric values for XGBoost
label_encoder = LabelEncoder()
y_comb_train_encoded = label_encoder.fit_transform(y_comb_train)
y_comb_test_encoded = label_encoder.transform(y_comb_test)

xgb_combined = xgb.XGBClassifier(eval_metric='mlogloss', random_state=42)
xgb_combined.fit(X_comb_train, y_comb_train_encoded)
y_comb_xgb_pred_encoded = xgb_combined.predict(X_comb_test)

# Decode predictions back to original labels
y_comb_xgb_pred = label_encoder.inverse_transform(y_comb_xgb_pred_encoded)

print("=== XGBoost on Combined Dataset with Proper Split ===")
print(classification_report(y_comb_test, y_comb_xgb_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_comb_test, y_comb_xgb_pred))
print(f"\nTrain size: {len(X_comb_train)}, Test size: {len(X_comb_test)}")
print(f"\nLabel mapping: {dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))}")

=== XGBoost on Combined Dataset with Proper Split ===
                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       281
           SITTING       0.97      0.98      0.97       263
          STANDING       0.98      0.97      0.97       359
           WALKING       0.97      0.98      0.97       272
WALKING_DOWNSTAIRS       0.98      0.99      0.98       204
  WALKING_UPSTAIRS       1.00      0.99      0.99       215

          accuracy                           0.98      1594
         macro avg       0.98      0.98      0.98      1594
      weighted avg       0.98      0.98      0.98      1594


Confusion Matrix:
[[281   0   0   0   0   0]
 [  0 257   5   1   0   0]
 [  0   8 348   3   0   0]
 [  0   0   2 266   3   1]
 [  0   0   0   3 201   0]
 [  0   0   0   1   1 213]]

Train size: 6375, Test size: 1594

Label mapping: {'LAYING': np.int64(0), 'SITTING': np.int64(1), 'STANDING': np.int64(2), 'WALKING': np.int64(3), 'WALKING_DOWN

## Model Comparison: Random Forest vs XGBoost

Both models achieve excellent **98% accuracy** on the combined dataset!

### Per-Class Performance Comparison:

| Activity | RF Precision | XGB Precision | RF Recall | XGB Recall |
|----------|--------------|---------------|-----------|------------|
| LAYING | 1.00 | 1.00 | 1.00 | 1.00 |
| SITTING | 0.94 | **0.97** ↑ | 0.96 | **0.98** ↑ |
| STANDING | 0.97 | **0.98** ↑ | 0.96 | **0.97** ↑ |
| WALKING | 0.97 | 0.97 | **0.99** | 0.98 |
| WALKING_DOWNSTAIRS | 0.99 | 0.98 | 0.97 | **0.99** ↑ |
| WALKING_UPSTAIRS | 0.99 | **1.00** ↑ | 1.00 | 0.99 |

### Key Differences:

**XGBoost advantages:**
- Better at SITTING (97% vs 94% precision) - fewer false positives
- Better at STANDING (98% vs 97% precision)
- Better at WALKING_DOWNSTAIRS recall (99% vs 97%)
- Perfect precision on WALKING_UPSTAIRS (100%)

**Random Forest advantages:**
- Slightly better WALKING recall (99% vs 98%)
- Both models perform equally well on LAYING (perfect scores)

### Conclusion:
Both models are production-ready with 98% accuracy. **XGBoost has a slight edge** on SITTING and STANDING classification, which were challenging activities in the original cross-dataset tests. For this dataset, either model would work well, but XGBoost may generalize slightly better.

In [6]:
# XGBoost on combined dataset but with kaggle test data
import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load datasets
combined_datasets = pd.read_csv("combined_dataset.csv")
kaggle_test_data = pd.read_csv("E:\\src\\neat-calculator\\kaggle_data\\human-activity-recognition-with-smartphones\\test.csv")

# Prepare combined dataset
X_combined = combined_datasets.drop("Activity", axis=1)
y_combined = combined_datasets["Activity"]

# Filter kaggle test data to match combined dataset columns
common_columns = [col for col in X_combined.columns if col in kaggle_test_data.columns]
print(f"Common columns: {len(common_columns)} out of {len(X_combined.columns)}")

X_kaggle_test = kaggle_test_data[common_columns]
y_kaggle_test = kaggle_test_data["Activity"]

# Encode labels to numeric values for XGBoost
label_encoder = LabelEncoder()
y_combined_encoded = label_encoder.fit_transform(y_combined)
y_kaggle_test_encoded = label_encoder.transform(y_kaggle_test)

# Train XGBoost on the combined dataset
xgb_combined = xgb.XGBClassifier(eval_metric='mlogloss', random_state=42)
xgb_combined.fit(X_combined[common_columns], y_combined_encoded)

# Predict on Kaggle test data
y_kaggle_xgb_pred_encoded = xgb_combined.predict(X_kaggle_test)

# Decode predictions back to original labels
y_kaggle_xgb_pred = label_encoder.inverse_transform(y_kaggle_xgb_pred_encoded)

print("=== XGBoost on Combined Dataset with Kaggle Test Data ===")
print(classification_report(y_kaggle_test, y_kaggle_xgb_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_kaggle_test, y_kaggle_xgb_pred))
print(f"\nKaggle Test size: {len(X_kaggle_test)}")
print(f"Features used: {len(common_columns)}")


Common columns: 180 out of 197
=== XGBoost on Combined Dataset with Kaggle Test Data ===
                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.92      0.85      0.88       491
          STANDING       0.87      0.94      0.90       532
           WALKING       0.87      0.92      0.89       496
WALKING_DOWNSTAIRS       0.95      0.87      0.91       420
  WALKING_UPSTAIRS       0.86      0.87      0.87       471

          accuracy                           0.91      2947
         macro avg       0.91      0.91      0.91      2947
      weighted avg       0.91      0.91      0.91      2947


Confusion Matrix:
[[537   0   0   0   0   0]
 [  0 415  74   0   0   2]
 [  0  34 498   0   0   0]
 [  0   0   0 457   5  34]
 [  0   0   0  26 365  29]
 [  0   1   1  44  15 410]]

Kaggle Test size: 2947
Features used: 180


In [7]:
# Baseline: XGBoost on Kaggle data alone (no user data added)
import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load Kaggle datasets only
kaggle_train_data = pd.read_csv("E:\\src\\neat-calculator\\kaggle_data\\human-activity-recognition-with-smartphones\\train.csv")
kaggle_test_data = pd.read_csv("E:\\src\\neat-calculator\\kaggle_data\\human-activity-recognition-with-smartphones\\test.csv")

# Prepare Kaggle training data
X_kaggle_train = kaggle_train_data.drop("Activity", axis=1)
y_kaggle_train = kaggle_train_data["Activity"]

# Prepare Kaggle test data  
X_kaggle_test = kaggle_test_data.drop("Activity", axis=1)
y_kaggle_test = kaggle_test_data["Activity"]

# Encode labels
label_encoder = LabelEncoder()
y_kaggle_train_encoded = label_encoder.fit_transform(y_kaggle_train)

# Train XGBoost on Kaggle data ONLY
xgb_kaggle_only = xgb.XGBClassifier(eval_metric='mlogloss', random_state=42)
xgb_kaggle_only.fit(X_kaggle_train, y_kaggle_train_encoded)

# Predict on Kaggle test data
y_pred_encoded = xgb_kaggle_only.predict(X_kaggle_test)
y_pred = label_encoder.inverse_transform(y_pred_encoded)

print("=== XGBoost on Kaggle Data ONLY (Baseline) ===")
print(classification_report(y_kaggle_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_kaggle_test, y_pred))
print(f"\nTrain size: {len(X_kaggle_train)}, Test size: {len(X_kaggle_test)}")


=== XGBoost on Kaggle Data ONLY (Baseline) ===
                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.94      0.84      0.89       491
          STANDING       0.87      0.95      0.91       532
           WALKING       0.93      0.98      0.96       496
WALKING_DOWNSTAIRS       0.97      0.92      0.94       420
  WALKING_UPSTAIRS       0.93      0.93      0.93       471

          accuracy                           0.94      2947
         macro avg       0.94      0.94      0.94      2947
      weighted avg       0.94      0.94      0.94      2947


Confusion Matrix:
[[537   0   0   0   0   0]
 [  0 413  75   0   0   3]
 [  0  26 506   0   0   0]
 [  0   0   0 486   6   4]
 [  0   0   0   9 385  26]
 [  0   1   0  25   5 440]]

Train size: 7352, Test size: 2947


In [8]:
# Fair comparison: Kaggle data with ONLY the 180 common features
import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load Kaggle datasets
kaggle_train_data = pd.read_csv("E:\\src\\neat-calculator\\kaggle_data\\human-activity-recognition-with-smartphones\\train.csv")
kaggle_test_data = pd.read_csv("E:\\src\\neat-calculator\\kaggle_data\\human-activity-recognition-with-smartphones\\test.csv")

# Use the same common_columns from the combined dataset test
# (We already have common_columns from the previous cell)
print(f"Using {len(common_columns)} common features for fair comparison")

# Prepare Kaggle training data with ONLY common features
X_kaggle_train = kaggle_train_data[common_columns]
y_kaggle_train = kaggle_train_data["Activity"]

# Prepare Kaggle test data with ONLY common features
X_kaggle_test = kaggle_test_data[common_columns]
y_kaggle_test = kaggle_test_data["Activity"]

# Encode labels
label_encoder = LabelEncoder()
y_kaggle_train_encoded = label_encoder.fit_transform(y_kaggle_train)

# Train XGBoost on Kaggle data with 180 features ONLY
xgb_kaggle_limited = xgb.XGBClassifier(eval_metric='mlogloss', random_state=42)
xgb_kaggle_limited.fit(X_kaggle_train, y_kaggle_train_encoded)

# Predict on Kaggle test data
y_pred_encoded = xgb_kaggle_limited.predict(X_kaggle_test)
y_pred = label_encoder.inverse_transform(y_pred_encoded)

print("=== XGBoost on Kaggle Data with 180 Features ONLY ===")
print(classification_report(y_kaggle_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_kaggle_test, y_pred))
print(f"\nTrain size: {len(X_kaggle_train)}, Test size: {len(X_kaggle_test)}")


Using 180 common features for fair comparison
=== XGBoost on Kaggle Data with 180 Features ONLY ===
                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.92      0.83      0.87       491
          STANDING       0.86      0.94      0.90       532
           WALKING       0.88      0.92      0.90       496
WALKING_DOWNSTAIRS       0.96      0.87      0.91       420
  WALKING_UPSTAIRS       0.87      0.90      0.88       471

          accuracy                           0.91      2947
         macro avg       0.91      0.91      0.91      2947
      weighted avg       0.91      0.91      0.91      2947


Confusion Matrix:
[[537   0   0   0   0   0]
 [  0 408  80   0   0   3]
 [  0  34 498   0   0   0]
 [  0   0   0 458   6  32]
 [  0   0   0  24 366  30]
 [  0   1   0  37  11 422]]

Train size: 7352, Test size: 2947


In [17]:
# MLflow autolog - automatically logs parameters, metrics, and models
import mlflow
import mlflow.sklearn
import mlflow.xgboost
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Enable autologging for sklearn and xgboost
mlflow.sklearn.autolog()
mlflow.xgboost.autolog()

# Set experiment
mlflow.set_experiment("HAR_Basic_Experiments")

# Load data
combined_datasets = pd.read_csv("combined_dataset.csv")
kaggle_test_data = pd.read_csv("E:\\src\\neat-calculator\\kaggle_data\\human-activity-recognition-with-smartphones\\test.csv")

X = combined_datasets.drop("Activity", axis=1)
y = combined_datasets["Activity"]

# Filter kaggle test data to match combined dataset columns
common_columns = [col for col in X.columns if col in kaggle_test_data.columns]
print(f"Common columns: {len(common_columns)} out of {len(X.columns)}")

X = X[common_columns]


# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Dataset ready: {len(X_train)} train, {len(X_test)} test")
print(f"Features: {X.shape[1]}, Classes: {len(y.unique())}")
print("\nMLflow autolog enabled - all experiments will be tracked automatically!")

Common columns: 180 out of 197
Dataset ready: 6375 train, 1594 test
Features: 180, Classes: 6

MLflow autolog enabled - all experiments will be tracked automatically!


In [11]:
# Experiment 1: Random Forest (autolog handles everything)
with mlflow.start_run(run_name="RandomForest_100"):
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    score = model.score(X_test, y_test)
    print(f"Random Forest accuracy: {score:.4f}")

Random Forest accuracy: 0.9768


In [18]:
# Experiment 2: XGBoost
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

with mlflow.start_run(run_name="XGBoost_default"):
    model = xgb.XGBClassifier(eval_metric='mlogloss', random_state=42)
    model.fit(X_train, y_train_encoded)
    score = model.score(X_test, y_test_encoded)
    print(f"XGBoost accuracy: {score:.4f}")

2026/01/12 21:14:58 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.


XGBoost accuracy: 0.9849


In [13]:
# View all experiments
runs_df = mlflow.search_runs(experiment_names=["HAR_Basic_Experiments"])
print(runs_df[['tags.mlflow.runName', 'metrics.training_score', 'params.n_estimators']].head())

print("\n\nTo view in MLflow UI:")
print("cd model_training")
print("mlflow ui")
print("Open: http://localhost:5000")

  tags.mlflow.runName  metrics.training_score params.n_estimators
0     XGBoost_default                     NaN                None
1    RandomForest_100                     1.0                 100


To view in MLflow UI:
cd model_training
mlflow ui
Open: http://localhost:5000


## Retrain Model on Database Features (180 features)

Train XGBoost on the exact 180 features stored in the database to match prediction pipeline.

## Production MLflow Setup

**Backend Store (PostgreSQL):** Stores experiment metadata, run info, parameters, metrics
**Artifact Store (Azure Blob):** Stores models, plots, and large files

Environment variables needed:
- `MLFLOW_BACKEND_STORE_URI`: PostgreSQL connection string
- `MLFLOW_ARTIFACT_URI`: Azure Blob Storage URI
- `AZURE_STORAGE_CONNECTION_STRING`: Azure credentials

In [1]:
# Configure MLflow with PostgreSQL + Azure Blob Storage
import os
from dotenv import load_dotenv
import mlflow

# Load environment variables
load_dotenv()

# Get URIs from environment
backend_store_uri = os.getenv('MLFLOW_BACKEND_STORE_URI', 'sqlite:///mlflow.db')  # Fallback to local
artifact_uri = os.getenv('MLFLOW_ARTIFACT_URI', './mlruns')  # Fallback to local

print(f"Backend Store: {backend_store_uri.split('@')[0]}...")  # Don't print password
print(f"Artifact Store: {artifact_uri}")

# Set tracking URI
mlflow.set_tracking_uri(backend_store_uri)

# Test connection
try:
    mlflow.search_experiments()
    print("✓ Successfully connected to MLflow backend")
except Exception as e:
    print(f"✗ Connection failed: {e}")
    print("Falling back to local SQLite")

Backend Store: postgresql+psycopg2://postgres:3NL2X%40w399c5qK...
Artifact Store: wasbs://mlflow-artifacts@harmlstorage.blob.core.windows.net


2026/01/14 13:55:13 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/01/14 13:55:13 INFO mlflow.store.db.utils: Updating database tables
2026/01/14 13:55:13 INFO alembic.runtime.migration: Context impl PostgresqlImpl.
2026/01/14 13:55:13 INFO alembic.runtime.migration: Will assume transactional DDL.
2026/01/14 13:55:14 INFO alembic.runtime.migration: Context impl PostgresqlImpl.
2026/01/14 13:55:14 INFO alembic.runtime.migration: Will assume transactional DDL.


✓ Successfully connected to MLflow backend


In [8]:
print(os.getenv('MLFLOW_BACKEND_STORE_URI'))
print(os.getenv('MLFLOW_ARTIFACT_URI'))
print(artifact_uri)

postgresql+psycopg2://postgres:3NL2X%40w399c5qK@har-ml-postgres.postgres.database.azure.com:5432/mlflow?sslmode=require
wasbs://mlflow-artifacts@harmlstorage.blob.core.windows.net
wasbs://mlflow-artifacts@harmlstorage.blob.core.windows.net


In [4]:
import sys
from pathlib import Path
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import mlflow
import mlflow.xgboost

# Add parent directory to path
project_root = Path().resolve().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from infra.db.database_utils import DatabaseFactory

# Load data from database (same source as prediction pipeline)
database_engine = DatabaseFactory.create_engine(
    db_type='sqlite',
    db_path=str(project_root / 'sensor_features.db')
)

data = database_engine.get_records(table_name="training_data_labeled")
print(f"Loaded {len(data)} rows from database")
print(f"Total columns: {len(data.columns)}")

# Drop non-feature columns
X = data.drop(["Activity", "timestamp"], axis=1)
y = data["Activity"]

print(f"\nFeature count: {X.shape[1]}")
print(f"Classes: {y.unique()}")
print(f"Class distribution:\n{y.value_counts()}")

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Encode labels
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

print(f"\nTrain size: {len(X_train)}, Test size: {len(X_test)}")
print(f"Label mapping: {dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))}")

Loaded 631 rows from database
Total columns: 182

Feature count: 180
Classes: ['STANDING' 'WALKING' 'WALKING_DOWNSTAIRS' 'SITTING' 'CUTOUT']
Class distribution:
Activity
STANDING              423
WALKING               132
WALKING_DOWNSTAIRS     34
SITTING                29
CUTOUT                 13
Name: count, dtype: int64

Train size: 504, Test size: 127
Label mapping: {'CUTOUT': np.int64(0), 'SITTING': np.int64(1), 'STANDING': np.int64(2), 'WALKING': np.int64(3), 'WALKING_DOWNSTAIRS': np.int64(4)}


In [10]:


# Train XGBoost and register with MLflow
artifact_uri = os.getenv('MLFLOW_ARTIFACT_URI', './mlruns')
print(f"Using artifact URI: {artifact_uri}")

# Set experiment with artifact location
experiment = mlflow.set_experiment("HAR_Production_Models3")
print(f"Experiment artifact location: {experiment.artifact_location}")

# If experiment artifact location is local, we need to create a new experiment or update it
if not experiment.artifact_location.startswith(('wasbs://', 'wasb://', 's3://', 'gs://')):
    print(f"⚠️  Experiment is using local storage: {experiment.artifact_location}")
    print("Creating a new experiment with Azure Blob Storage...")
    
    # Create a new experiment with the correct artifact location
    try:
        experiment_id = mlflow.create_experiment(
            "HAR_Production_Models3",
            artifact_location=artifact_uri
        )
        mlflow.set_experiment("HAR_Production_Models3")
        print(f"✓ Created new experiment with artifact location: {artifact_uri}")
    except:
        # If experiment already exists, just set it
        mlflow.set_experiment("HAR_Production_Models3")

with mlflow.start_run(run_name="XGBoost_180_features") as run:
    # Train model
    model = xgb.XGBClassifier(
        eval_metric='mlogloss',
        random_state=42,
        n_estimators=100,
        max_depth=6,
        learning_rate=0.3
    )
    model.fit(X_train, y_train_encoded)
    
    # Evaluate
    y_pred_encoded = model.predict(X_test)
    y_pred = label_encoder.inverse_transform(y_pred_encoded)
    
    accuracy = model.score(X_test, y_test_encoded)
    
    # Log metrics
    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_param("n_features", X.shape[1])
    mlflow.log_param("n_classes", len(label_encoder.classes_))
    
    # Log model with signature (will be saved to Azure Blob)
    from mlflow.models.signature import infer_signature
    signature = infer_signature(X_train, model.predict(X_train))
    
    mlflow.xgboost.log_model(
        model,
        artifact_path="model",
        signature=signature,
        registered_model_name="HAR_xgboost"
    )
    
    print(f"\n=== XGBoost Model Training Complete ===")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"\nClassification Report:")
    print(classification_report(y_test, y_pred))
    print(f"\nRun ID: {run.info.run_id}")
    print(f"Model registered as: HAR_xgboost")
    print(f"Artifacts stored at: {run.info.artifact_uri}")


Using artifact URI: wasbs://mlflow-artifacts@harmlstorage.blob.core.windows.net
Experiment artifact location: wasbs://mlflow-artifacts@harmlstorage.blob.core.windows.net


2026/01/14 14:04:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Registered model 'HAR_xgboost' already exists. Creating a new version of this model...
Created version '5' of model 'HAR_xgboost'.



=== XGBoost Model Training Complete ===
Accuracy: 0.8504

Classification Report:
                    precision    recall  f1-score   support

            CUTOUT       1.00      1.00      1.00         3
           SITTING       0.50      0.17      0.25         6
          STANDING       0.88      0.94      0.91        85
           WALKING       0.73      0.73      0.73        26
WALKING_DOWNSTAIRS       1.00      0.71      0.83         7

          accuracy                           0.85       127
         macro avg       0.82      0.71      0.74       127
      weighted avg       0.84      0.85      0.84       127


Run ID: 7ceacee2264c440b8df6fcd136ba23c4
Model registered as: HAR_xgboost
Artifacts stored at: wasbs://mlflow-artifacts@harmlstorage.blob.core.windows.net/7ceacee2264c440b8df6fcd136ba23c4/artifacts


In [21]:
# Set the 'production' alias to the latest version
from mlflow.tracking import MlflowClient

client = MlflowClient()

# Get the latest version of the registered model
model_name = "HAR_xgboost"
latest_versions = client.get_latest_versions(model_name, stages=["None"])

if latest_versions:
    latest_version = latest_versions[0].version
    
    # Set alias to 'production'
    client.set_registered_model_alias(
        name=model_name,
        alias="production",
        version=latest_version
    )
    
    print(f"✓ Set 'production' alias to version {latest_version} of {model_name}")
    print(f"\nModel URI: models:/{model_name}@production")
else:
    print("No model versions found. Run the training cell above first.")

✓ Set 'production' alias to version 4 of HAR_xgboost

Model URI: models:/HAR_xgboost@production


C:\Users\patry\AppData\Local\Temp\ipykernel_18144\3860262998.py:8: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  latest_versions = client.get_latest_versions(model_name, stages=["None"])
